name: Windows CI Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    env:
      GITHUB_WORKSPACE: C:\a
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_DISABLE_METRICS: 1
      VCPKG_DEFAULT_TRIPLET: x64-windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.25.0"

      - name: Install Windows dependencies
        run: |
          choco install ninja doxygen.install python3 -y --no-progress

      - name: Cache vcpkg binaries
        id: vcpkg-cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.VCPKG_ROOT }}\installed
            ${{ env.VCPKG_ROOT }}\buildtrees
            ${{ env.VCPKG_ROOT }}\packages
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

      - name: Setup vcpkg
        if: steps.vcpkg-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg.git "$env:VCPKG_ROOT"
          cd "$env:VCPKG_ROOT"
          git checkout 8f63c9ed5897d7367a92a442a79f91721e0fd38f
          .\bootstrap-vcpkg.bat -disableMetrics
          .\vcpkg integrate install

      - name: Install dependencies
        if: steps.vcpkg-cache.outputs.cache-hit != 'true'
        run: |
          cd "$env:VCPKG_ROOT"
          .\vcpkg install --feature-flags=versions --debug

      - name: Configure and build with MSVC environment
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          cmake --preset windows-base
          cmake --build --preset windows-verbose-build
